### ISSUE TITLE
Cargo build error

### ISSUE THREAD

**Issue by smillies** [iharsuvorau/event-log-converter#1]
Hello there,

after downloading the project and trying to build it with `cargo build` I get the following error:

> error[E0554]: `#![feature]` may not be used on the stable release channel
>  --> src/lib.rs:1:12
>    |
> 1 | #![feature(slice_group_by)]
>    |

Could you change this so that it is possible to use a stable release?

Regards,
Sebastian

**Comment by iharsuvorau** [comment]
Hi @smillies. Thanks for the interest! I'm not changing it now. It's not that difficult to switch to a nightly release for a project that uses `event-log-converter`: https://stackoverflow.com/questions/67094650/set-a-project-to-use-nightly-by-default
